gnss_baudrate: 115200
gnss_aquire_rate: 10
gnss_enabled: {GPS: {min: 8, max: 16, sig: 0x1}, SBAS: {min: 1, max: 3, sig: 0x1}, GLONASS: {min: 8, max: 14, sig: 0x1}}
gnss_enable_sbas: true
gnss_enable_ppp: false
gnss_dynamic_model: "pedestrian"
gnss_fix_mode: "both"
gnss_dr_limit: 0
gnss_ublox_version: 8

init_reset: true

odo_enable: false
odo_lowspeed_cog: true
odo_lp_vel: true
odo_lp_cog: true
odo_lp_vel_gain: 1
odo_lp_cog_gain: 1
odo_lowspeed_max_speed: 1
odo_lowspeed_max_pos_acc: 1

# massages allowed in M8P. See "u-blox8-M8_ReceiverDescrProtSpec_(UBX-13003221)_Public"
all: false
#mga: false
rxm: false
nav: false
aid: false

#mga_gps_eph: true

nav_timegps: true
nav_timeutc: true
nav_sol: true
nav_status: true
nav_svinfo: false
nav_clk: true
nav_posllh: true
nav_velned: true
nav_orb: true
nav_pvt: true
nav_sbas: true
nav_dgps: true
nav_sat: true
nav_dop: true

#rxm_raw: false
rxm_rawx: false
rxm_sfrbx: false
rxm_svsi: false

aid_alm: true
aid_eph: true
aid_hui: true
